name: Sync with S3

description:
  Sync code with S3 bucket

inputs:
  deploy-bucket:
    description: "S3 bucket to deploy to"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: sync s3 code with s3 bucket
      run: |
        aws s3 sync . s3://${{ inputs.deploy-bucket }} --quiet --delete \ 
        --exclude ".git/*" --exclude ".github/*" --exclude ".idea/*"
      shell: bash
