name: deploy-s3
on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Sync code with S3 main bucket
        if: github.ref == 'refs/heads/main'
        uses: "./.github/sync-s3"
        with:
          deploy-bucket: "train.jarivanmelckebeke.be"

      - name: Sync code with S3 preview bucket
        if: github.ref != 'refs/heads/main'
        uses: "./.github/sync-s3"
        with:
          deploy-bucket: "train-preview.jarivanmelckebeke.be"
