name: deploy-s3
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Sync code with S3 main bucket
        if: github.ref == 'refs/heads/main'
        uses: "./.github/actions/action.yaml"
        with:
          deploy-bucket: "train.jarivanmelckebeke.be"

      - name: Sync code with S3 preview bucket
        if: github.ref != 'refs/heads/main'
        uses: "./.github/actions/action.yaml"
        with:
          deploy-bucket: "train-preview.jarivanmelckebeke.be"
